kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-prometheus
  namespace: {{ .Values.namespace }}
data:
  config: |+
    global:
      scrape_interval: "1m"
      scrape_timeout: "10s"
      evaluation_interval: "1m"
    scrape_configs:
    - job_name: GrappaInfluxDb
      metrics_path: /monitor
      honor_labels: false
      honor_timestamps: true
      scheme: http
      follow_redirects: true
      body_size_limit: 0
      sample_limit: 0
      label_limit: 0
      label_name_length_limit: 0
      label_value_length_limit: 0
      target_limit: 0
      basic_auth:
        username: "monitor"
        password: "asd"
      static_configs:
        - targets:
          - "{{ .Values.GrappaDeployment.name }}:{{ .Values.GrappaDeployment.influxdb.service.targetPort }}"
    - job_name: GrappaMySql
      metrics_path: /monitor
      honor_labels: false
      honor_timestamps: true
      scheme: http
      follow_redirects: true
      body_size_limit: 0
      sample_limit: 0
      label_limit: 0
      label_name_length_limit: 0
      label_value_length_limit: 0
      target_limit: 0
      basic_auth:
        username: "monitor"
        password: "asd"
      static_configs:
        - targets:
          - "{{ .Values.GrappaDeployment.mysql.name }}:{{ .Values.GrappaDeployment.mysql.service.targetPort }}"