apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.GrafanaDeployment.name }}
                port:
                    number: {{ .Values.GrafanaDeployment.service.port }}
      - path: /influxdb
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.DatabasesDeployment.InfluxDb.name }}
                port:
                    number: {{ .Values.DatabasesDeployment.InfluxDb.service.port }}
      - path: /mysql
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.DatabasesDeployment.MySQL.name }}
                port:
                    number: {{ .Values.DatabasesDeployment.MySQL.service.port }}