apiVersion: v1
kind: Secret
metadata:
  name: secret-influxdb
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ .Values.DatabasesDeployment.InfluxDb.password }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.DatabasesDeployment.InfluxDb.token }}