apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.DataGenerator.name }}
type: Opaque
stringData:
  TOKEN: {{ .Values.DatabasesDeployment.InfluxDb.token }}
  MYSQL_USERNAME: {{ .Values.DatabasesDeployment.MySQL.username }}
  MYSQL_PASSWORD: {{ .Values.DatabasesDeployment.MySQL.password }}
  