apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.DatabasesDeployment.MySQL.username }}
  MYSQL_PASSWORD: {{ .Values.DatabasesDeployment.MySQL.password }}
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_DATABASE: {{ .Values.DatabasesDeployment.MySQL.database }}
  