apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  ingressClassName: nginx
  rules:
  - host: "grafana.grappa.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.GrafanaDeployment.name }}
                port:
                    number: {{ .Values.GrafanaDeployment.service.port }}
