name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  docker_push:
    runs-on: ubuntu-latest
    steps:
    - name: DockerHub login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Grappa
      working-directory: ./app
      run: docker build . --file Dockerfile --tag zsemi02/grappa:${{ github.event.release.tag_name }}
    - name: Build and push Grappa-datagenerator
      working-directory: ./test
      run: docker build . --file Dockerfile --tag zsemi02/grappa-datagenerator:${{ github.event.release.tag_name }}

