name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  docker_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: DockerHub login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Grappa
      working-directory: ${{ github.workspace }}/app
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/grappa:${{ github.event.release.tag_name }}
    - name: Build and push Grappa-datagenerator
      working-directory: ${{ github.workspace }}/test
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/grappa-datagenerator:${{ github.event.release.tag_name }}

